# Generated by Django 5.2.13 on 2026-04-25 14:34

import django.core.validators
import django.db.models.deletion
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('rutas_asignadas', models.ManyToManyField(blank=True, to='rutas.ruta', verbose_name='Rutas Asignadas')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda], verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo], verbose_name='Peso (kg)')),
                ('volumen_cm3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volumen (cm³)')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('TRA', 'En tránsito'), ('ENT', 'Entregado'), ('DEV', 'Devuelto')], default='PEN', max_length=3, verbose_name='Estado')),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de Envío')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_entrega_est', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Real')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='envios_como_destinatario', to='clientes.cliente', verbose_name='Destinatario')),
                ('empleado_registro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='envios.empleado', verbose_name='Empleado que Registra')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='envios_como_remitente', to='clientes.cliente', verbose_name='Remitente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rutas.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'db_table': 'encomiendas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PEN', 'Pendiente'), ('TRA', 'En tránsito'), ('ENT', 'Entregado'), ('DEV', 'Devuelto')], max_length=3, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('PEN', 'Pendiente'), ('TRA', 'En tránsito'), ('ENT', 'Entregado'), ('DEV', 'Devuelto')], max_length=3, verbose_name='Estado Nuevo')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='envios.empleado', verbose_name='Empleado que registra')),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='envios.encomienda', verbose_name='Encomienda')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estado',
                'db_table': 'historial_estados',
            },
        ),
    ]
