# Generated by Django 5.2.13 on 2026-04-25 16:57

import django.db.models.deletion
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_options_alter_cliente_direccion_and_more'),
        ('envios', '0002_alter_empleado_estado_alter_encomienda_estado_and_more'),
        ('rutas', '0003_alter_ruta_options_alter_ruta_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellidos'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='historialestado',
            options={'ordering': ['-fecha_cambio']},
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE empleados SET estado = '1' WHERE estado = 'ACT';"
                "UPDATE empleados SET estado = '9' WHERE estado = 'INA';"
            ),
            reverse_sql=(
                "UPDATE empleados SET estado = 'ACT' WHERE estado = '1';"
                "UPDATE empleados SET estado = 'INA' WHERE estado = '9';"
            ),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(max_length=80, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda], verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Envio'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_destinatario', to='clientes.cliente', verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='empleado_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_registradas', to='envios.empleado', verbose_name='Empleado que Registra'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En transito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], default='PE', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='fecha_entrega_est',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='fecha_entrega_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Real'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_remitente', to='clientes.cliente', verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas', to='rutas.ruta', verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='volumen_cm3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volumen (cm3)'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to='envios.empleado', verbose_name='Empleado que registra'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='encomienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='envios.encomienda', verbose_name='Encomienda'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En transito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], max_length=2, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En transito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], max_length=2, verbose_name='Estado Nuevo'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observacion'),
        ),
    ]
