# Generated by Django 5.2.13 on 2026-04-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterField(
            model_name='ruta',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(max_length=100, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='dias_entrega',
            field=models.PositiveIntegerField(verbose_name='Días de Entrega'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activo'), ('INA', 'De baja')], default='ACT', max_length=3, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(max_length=100, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio Base'),
        ),
    ]
