# Generated by Django 5.2.13 on 2026-04-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_alter_ruta_options_alter_ruta_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['origen', 'destino'], 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE rutas SET estado = '1' WHERE estado = 'ACT';"
                "UPDATE rutas SET estado = '9' WHERE estado = 'INA';"
            ),
            reverse_sql=(
                "UPDATE rutas SET estado = 'ACT' WHERE estado = '1';"
                "UPDATE rutas SET estado = 'INA' WHERE estado = '9';"
            ),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='dias_entrega',
            field=models.PositiveIntegerField(default=1, verbose_name='Dias de Entrega'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base'),
        ),
    ]
