# Generated by Django 5.2.13 on 2026-04-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activo'), ('INA', 'De baja')], default='ACT', max_length=3, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_doc',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('PAS', 'Pasaporte')], default='DNI', max_length=3, verbose_name='Tipo de Documento'),
        ),
    ]
