# Generated by Django 5.2.13 on 2026-04-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_estado_alter_cliente_tipo_doc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE clientes SET estado = '1' WHERE estado = 'ACT';"
                "UPDATE clientes SET estado = '9' WHERE estado = 'INA';"
            ),
            reverse_sql=(
                "UPDATE clientes SET estado = 'ACT' WHERE estado = '1';"
                "UPDATE clientes SET estado = 'INA' WHERE estado = '9';"
            ),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nro_doc',
            field=models.CharField(max_length=15, unique=True, verbose_name='Numero de Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono'),
        ),
    ]
